README.md, _layouts/default.html, assets/css/style.scss
Adds an index to the README with links to specific design files
=> Updated readme and theme for better browsing experience

_layouts/default.html
Corrects capitalization of OpenShift on the documentation pages.
=> Correcting capitalization

_config.yml, _layouts/default.html, assets/css/style.scss
Updates styling for GH Pages to remove unnecessary color and use more PatternFly-ish styling.
=> Update gh-pages styling

README.md, assets/css/style.scss, web-console/1-homepage/catalog.md, web-console/1-homepage/offerings.md, web-console/1-homepage/overview.md, web-console/1-homepage/project-panel.md, web-console/1-homepage/search.md, web-console/2-projects-page/overview.md, web-console/3-project-details/add-to-project.md, web-console/3-project-details/binding-in-project.md, web-console/3-project-details/overview.md, web-console/3-project-details/provisioned-services.md, web-console/4-patterns/bind.md, web-console/4-patterns/masthead.md, web-console/4-patterns/navigation.md, web-console/4-patterns/overlay-panel.md, web-console/5-components/order-from-catalog.md
Minor style updates and replaces spaces with tabs for easier formatting/editing
=> Converting whitespace to tabs for easier formatting

README.md
Adds homepage links to two new documentation sets
=> Adding links to new content

README.md
updating the readme file @serenamarie125
=> Updating the Readme file to display new "Add-to-Application" section

README.md
@serenamarie125 This adds the route stuff to the readme file.
=> Added link for select route to readme file

README.md, web-console/conceptual-designs/cnv.md, web-console/conceptual-designs/mobile.md
- Added a new section for Conceptual Designs
- Created a page for linking the invision flows for CNV 
- Created a page for linking the invision flows for Mobile
=> Adds Conceptual Design section with two pages under it: CNV and mobile

web-console/conceptual-designs/catalog.md, web-console/conceptual-designs/cnv.md, web-console/conceptual-designs/mobile.md
Adds some info and a link to the current mockups for the catalog redesign.
Adds more detail to the notes for the mobile integration section
Fixes link formatting
=> Adding catalog concepts and cleaning up

README.md, web-console/conceptual-designs/pull-secret.md
Proposal for giving users the ability to create a pull secret as part of the deploy image flow.
=> Conceptual design for adding pull secret to deploy image flow

web-console/project-details/edit-yaml.md
Adding designs for a new YAML tab on the detail pages inside the console. Also includes future changes we will need to make in order to be consistent on all terminal/editor-type views. 
@ncameronbritt @serenamarie125 @cshinn @spadgett please take a look!
=> Adding YAML editor 

README.md, web-console/project-details/membership.md
Adds designs for a new role details page as well as changes to the membership page that bring it more in-line with existing console pages
=> Adding membership and role details

web-console/conceptual-designs/cnv.md
Adding a link to the latest invision flow and (view and manage VMs) and I also split up the original invision link into two sections since it was very lengthy.
@serenamarie125 @cshinn Please review!
=> Updating CNV invision flows to provide latest console designs

web-console/conceptual-designs/mobile.md
Updates the wireframe link and adds several new mobile use cases reflected in the wireframes
=> Update mobile use cases and wireframe link

README.md, web-console/conceptual-designs/topology.md
Adds a conceptual design page for the topology view and a link to that page from the readme file
=> Add topology view concepts and link

README.md, web-console/4.0-designs/status/status.md
@serenamarie125 Sorry I made a mistake saving over my file earlier and Brie noticed I had a bunch of issues with my file. Second time's a charm :) Can you merge when you get a chance? This should resolve the previous errors.
=> Fixing errors from earlier PR

README.md
@serenamarie125 This should do it! :)
=> Fixing Code Editors link in README

README.md
Updating READme file, @serenamarie125 please review and merge when you get a chance! Just fixing broken links.
=> Updating READme file

README.md
@cshinn @bmignano Please take a look and see if this resolves the issues we found. 
FYI @serenamarie125
=> Fixing Broken Links in the Design Documentation

.github/pull_request_template.md
Sorry @beanh66, looks like I forgot a "that" in the original PR. I also tweaked the first two sentences to read slightly smoother.
=> Fix PR template wording

README.md, web-console/developer/add/add.md, web-console/developer/advanced/advanced.md, web-console/developer/builds/builds.md, web-console/developer/developer.md, web-console/developer/pipelines/pipelines.md, web-console/developer/topology/topology.md
Including the intitial PR for the dev console.  @beanh66 I only have a single change to README.md to mimimize the amount of conflicts between teams.  Please take a look and merge asap if you agree with this approach so we can continue with further PRs, thank you!
=> Initial PR for dev console

README.md
create link in the readme.md for "link between pvc and vm disk"
=> Add links for Exposing Secrets and PVC/VM Disk Link

README.md
fixes link issues with Create VM and VM details
=> little updates

web-console/knikubevirt/knikubevirt.md
The Console designs are now included in the VM details design.
=> removes console item

web-console/knikubevirt/knikubevirt.md
quick update to link to import flow that got dropped at some point.
=> import link added

web-console/knikubevirt/Create-vm/step-1-genaral/wizard-general.md
=> removes section titles

web-console/knikubevirt/Create-vm/step-3-storage/wizard-storage.md
This is just adding headings to each type so we can easily link to them for reference.
=> minor update

web-console/knikubevirt/knikubevirt.md
=> missing advanced link

web-console/knikubevirt/knikubevirt.md
Just cleaning up the CNV readme a bit and adding a missing link for the storage class designs.
Optional team mentions (include any that are related to this PR):
@openshift/team-ux-review (Admin Console UX team)
@openshift/team-kni-ux (KNI & KubeVirt UX team)
=> updates readme

web-console/knikubevirt/vm-details/vm-boot-order/vm-boot-order.md
Fix image url typo in boot order design
=> Fix image url typo in boot order design

virtualization/virtualization.md
A few new updates to our readme to prep for new designs coming.
=> small virt readme update

conventions/documentation/componentstatus.md
Pulls in the changes from [this last Storybook PR](https://github.com/rh-uxd/openshift-storybook/pull/16).
FYI @beanh66 @rachael-phillips
=> Update PF component table

designs/developer/add-43/Container-Image/Deploy-Image.md, designs/developer/add-43/index.md, designs/developer/add-44/Container-Image/Deploy-Image.md, designs/developer/add-44/index.md, designs/developer/add/index.md, designs/developer/index.md
=> update formatting of dev index

designs/developer/index.md
=> remove angle brackets

designs/developer/index.md
more dev updates - don't use .md in main index file
=> more dev updates - don't use .md in main index file

designs/developer/index.md, designs/developer/operator-pipeline-42/index.md, designs/developer/operator-pipeline-42/pipelines.md, designs/developer/operator-pipeline-43/index.md, designs/developer/operator-pipeline-44/index.md, designs/developer/operator-pipeline-44/pipeline-builder.md
update typo on pipeline directory
=> update typo on pipeline directory

designs/developer/add-44/From-Catalog/Add-from-catalog.md
fix a problem w add-from-catalog
=> fix a problem w add-from-catalog

designs/developer/add-45/index.md, designs/developer/add-45/sections/Adv-Health_Checks.md, designs/developer/index.md
Write a sentence or two describing what this PR includes along with any additional information that could be helpful to reviewers.
Created an add-45 directory with an index.md file. Also created a sections directory within this directory with a Adv-Health_Checks.md page for a new Heath Checks section on the Add forms. Note: This is a test PR for a meeting my team is having tomorrow to discuss documentation. 
Check to make sure the top of your PR has the correct Parent (Administrator, Developer, etc.) and Version (4.0, 4.x, etc.). If this design is a conceptual design with no clear release date, the parent should be "Concepts".
If this PR fixes an [issue](https://github.com/openshift/openshift-origin-design/issues), include a [keyword](https://help.github.com/en/articles/closing-issues-usin …
=> 45 dev console - add flow

designs/developer/add-45/From-Catalog/Catalog-HelmChart.md, designs/developer/add-45/index.md, designs/developer/add-45/sections/pipelines.md, designs/developer/helm-45/index.md, designs/developer/index.md, designs/developer/operator-pipeline-45/pipelines.md, designs/developer/operator-serverless-45/index.md, designs/developer/operator-serverless-45/knative-services-add.md, designs/developer/search-45/index.md
Write a sentence or two describing what this PR includes along with any additional information that could be helpful to reviewers.
This PR creates the framework for 4.5 documentation. PRs will be opened subsequently to fill out the 4.5 design for the stories in this sprint. This framework consists of new and updated .md files that will be further updated by individual designers.
Check to make sure the top of your PR has the correct Parent (Administrator, Developer, etc.) and Version (4.0, 4.x, etc.). If this design is a conceptual design with no clear release date, the parent should be "Concepts".
If this PR fixes an [issue](https://github.com/openshift/openshift-origin-design/issues), include a [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically …
=> 4.5 Developer - framework for our documentation

conventions/documentation/capitalization.md
Adding guidelines for capitalization in the console UI.
=> Adding capitalization to conventions

research/competitive_interviews/index.md, research/operator_mental_models_and_personas/index.md
Added sensitive projects with link-only pages that go to fire-walled documents
For projects we don't want open-sourced (yet), I'm adding links here to keep track of existing research all in one place.
=> Adding internal projects

designs/virtualization/4.x/create-vm-dropdowns/create-vm-dropdowns.md
fixes a spelling error and image path
@openshift/team-ux-review (Administrator perspective)
@openshift/team-kni-ux (KNI & Virtualization)
=> fixes broken image

designs/administrator/4.6/cluster-settings/index.md
Fixed a typo so the project will show up under Admin 4.6.
=> Fixed typo 

designs/developer/index.md, releases/index.md, research/index.md
File was removed by mistake
/developer/index.md
@openshift/team-ux-review (Administrator perspective)
@openshift/team-kni-ux (KNI & Virtualization)
=> add mistakenly deleted index.md file

conventions/index.md
Deleted conventions index file
@openshift/team-ux-review (Administrator perspective)
@openshift/team-kni-ux (KNI & Virtualization)
=> conventions index file

designs/developer/4.7/argo-cd-link/index.md, designs/developer/4.7/quick-starts-catalog/index.md, designs/developer/4.7/quick-starts-navigation-hints/index.md
Updated the header since that appeared to be causing issues in the last PR.
=> Updating header for 4.7 features- ArgoCD link, Quick Starts catalog, and hints

conventions/documentation/quick-starts.md
This PR updates a few things in the quick start guidelines:
* Updates links in table of contents
* Removes mentions of quick start template
* Other minor edits
=> Updating quick start guidelines

conventions/documentation/actionmenus.md
Updating our actions menu convention to include documentation on when to hide or disable actions within the console.
@openshift/team-ux-review (Administrator perspective)
@openshift/team-kni-ux (KNI & Virtualization)
=> Adding additional actions guidelines
